language: node_js

node_js:
  - node
  - lts/erbium
  - lts/dubnium

services:
  - mysql

branches:
  only:
    - master

env: >
  NODE_ENV=test
  APP_NAME='Node JS Starter'
  APP_VERSION='1.0.0'
  TEST_APP_PORT='9945'
  TEST_DB_NAME='app_test'
  TEST_DB_PASSWORD=''
  TEST_DB_PORT='3306'
  TEST_DB_USER='mysql'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - cp .env.example .env
  - yarn migrate

script:
  - yarn test:coverage

after_script:
  - yarn codecov
